apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=        # postgres (base64)
  POSTGRES_PASSWORD: cG9zdGdyZXM=    # postgres (base64)
  POSTGRES_DB: bXlkYg==              # mydb (base64)
