{{- $root := . -}}
{{- range $cmName, $cmData := $root.Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmName }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "helm-app.labels" $root | nindent 4 }}
data:
{{- range $key, $value := $cmData }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end }}
---
{{- end }}