{{- $root := . -}}
{{- range $hpaName, $hpa := $root.Values.hpas }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $hpaName }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "helm-app.labels" $root | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $hpa.targetDeployment }}
  minReplicas: {{ $hpa.minReplicas }}
  maxReplicas: {{ $hpa.maxReplicas }}
  metrics:
  {{- if $hpa.cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $hpa.cpu.targetAverageUtilization }}
  {{- end }}
  {{- if $hpa.memory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $hpa.memory.targetAverageUtilization }}
  {{- end }}
---
{{- end }}
