{{- $root := . -}}
{{- range $secretName, $secretData := $root.Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "helm-app.labels" $root | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
{{- end }}
